#!/bin/bash

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# chkconfig: 2345 80 20
# description: Summary: ZooKeeper is a centralized service for maintaining configuration information, naming, providing distributed synchronization, and providing group services. All of these kinds of services are used in some form or another by distributed applications. Each time they are implemented there is a lot of work that goes into fixing the bugs and race conditions that are inevitable. Because of the difficulty of implementing these kinds of services, applications initially usually skimp on them ,which make them brittle in the presence of change and difficult to manage. Even when done correctly, different implementations of these services lead to management complexity when the applications are deployed.
# processname: java
# pidfile: /var/run/zookeeper/zookeeper_server.pid
### BEGIN INIT INFO
# Provides:          zookeeper-server
# Required-Start:    $network $local_fs
# Required-Stop:
# Should-Start:      $named
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: ZooKeeper is a centralized service for maintaining configuration information, naming, providing distributed synchronization, and providing group services.
### END INIT INFO

NAME='Zookeeper Server'
USER='zookeeper'
CONF_DIR='/usr/hdp/current/zookeeper-server/conf'
PID_FILE='/var/run/zookeeper/zookeeper_server.pid'
CMD="su - $USER -c \"export ZOOCFGDIR=$CONF_DIR; export ZOOCFG=zoo.cfg; source $CONF_DIR/zookeeper-env.sh; /usr/hdp/current/zookeeper-server/bin/zkServer.sh start\""

function start {
  if [ -f $PID_FILE ]; then
    pid=`cat $PID_FILE`
    echo $pid
    if kill -0 $pid >/dev/null 2>&1 $pid; then
       echo "$NAME already started"
       exit 3
    else
      rm -rf $PID_FILE
    fi
  fi
  eval $CMD
  #echo $! > $PID_FILE
  echo "$NAME started [`cat $PID_FILE`]"
}

function stop {
  kill $(<$PID_FILE) 2>/dev/null
  if [[ $? -eq 1 ]]; then
    echo "$NAME already stopped"
  else
    rm $PID_FILE
    echo "$NAME stopped"
  fi
}

function status {
  if [ -f $PID_FILE ]; then
    pid=`cat $PID_FILE`
    if kill -0 >/dev/null 2>&1 $pid; then
       echo "$NAME started [$PID_FILE]"
       exit 0
    fi
  fi
  echo "$NAME stopped"
  exit 3
}

if [[ $1 == "start" ]]; then
  start "$@"
elif [[ $1 == "stop" ]]; then
  stop "$@"
elif [[ $1 == "restart" ]]; then
  stop "$@"
  start "$@"
elif [[ $1 == "status" ]]; then
  status "$@"
else
  N=/etc/init.d/$NAME
  echo "Usage: $N {start|stop|restart|status}" >&2
fi

