#!/bin/bash

# Documentation
# http://docs.hortonworks.com/HDPDocuments/HDP1/HDP-1.2.1/bk_using_Ambari_book/content/ambari-chap1-6.html
# http://docs.hortonworks.com/HDPDocuments/HDP1/HDP-1.3.0/bk_reference/content/deployinghdp_appendix_chap4_3_2_2.html

if [ -z "$1" ]; then
  fqdn=`hostname`
else
  fqdn=$1
fi

function print {
  if [ -t 1 ]
  then echo -e "\e[1;34m$1\e[0m"; 
  else echo -e "$1";
  fi
}

# Download a repository locally, back it up and replace HortonWorks fqdn with local fqdn
# Arguments are
# $1 Repo name (for debuging)
# $2 URL of the repo
function repo {
  print 'Download '$1
  curl $2 -o /etc/yum.repos.d/$(basename $2)
  print 'Copy '$1
  cp -rp /etc/yum.repos.d/$(basename $2) /etc/yum.repos.d.temp/$(basename $2)
  sed -i s/[0-1a-z\-]*.hortonworks.com/$fqdn/g /etc/yum.repos.d.temp/$(basename $2)
}

function push {
  httppath=/var/www/html
  reponame=$1
  print $reponame' Prepare'
  repopath=$2
  repopath=${repopath/http:\/\/}
  repopath=/${repopath#*\/}
  print $reponame' Sync'
  mkdir -p $httppath$repopath
  reposync -n -g -r $reponame -p $httppath$repopath
  cd $httppath$repopath
  createrepo .
  if [ -n "$3" ]; then
    keyurl=$3
    keypath=${keyurl/http:\/\/}
    keypath=/${keypath#*\/}
    print $reponame' Key'
    mkdir -p `dirname $httppath$keypath`
    curl $keyurl -o $httppath$keypath
  fi
}

# ############## PREPARE ##############

print 'Move current repositories'
mkdir -p /etc/yum.repos.d.temp
mv /etc/yum.repos.d/* /etc/yum.repos.d.temp

print 'Set proxy'
export http_proxy=http://noevipncp2a.edf.fr:3128

print 'Install Yum priorities'
curl http://mirror.centos.org/centos/6/os/i386/Packages/yum-plugin-priorities-1.1.30-14.el6.noarch.rpm -o /tmp/yum-plugin-priorities-1.1.30-14.el6.noarch.rpm
rpm -ivh /tmp/yum-plugin-priorities-1.1.30-14.el6.noarch.rpm
rm -rf /tmp/yum-plugin-priorities-1.1.30-14.el6.noarch.rpm
cat > /etc/yum/pluginconf.d/priorities.conf <<PRIORITIES
[main]
enabled=1
gpgcheck=0
PRIORITIES

# ############## REPO ##############

repo 'HDP repository' \
  'http://public-repo-1.hortonworks.com/HDP/centos6/2.x/updates/2.0.6.0/hdp.repo'
  # 'http://public-repo-1.hortonworks.com/HDP/centos6/2.x/updates/2.0.5.0/hdp.repo'
  # 'http://public-repo-1.hortonworks.com/HDP/centos6/1.x/GA/1.3.0.0/hdp.repo'

# ############## CLEANUP ##############

print 'Clean Yum metadata and list repositories'
yum clean metadata
yum repolist

# ############## DOWNLOAD ##############

push 'HDP-2.x' \
  'http://public-repo-1.hortonworks.com/HDP/centos6/2.x/GA' \
  'http://public-repo-1.hortonworks.com/HDP/centos6/RPM-GPG-KEY/RPM-GPG-KEY-Jenkins'
  # 'http://public-repo-1.hortonworks.com/HDP/centos6/1.x/GA' \
  # 'http://public-repo-1.hortonworks.com/HDP/centos6/RPM-GPG-KEY/RPM-GPG-KEY-Jenkins'

push 'HDP-UTILS-1.1.0.16' \
  'http://public-repo-1.hortonworks.com/HDP-UTILS-1.1.0.16/repos/centos6' \
  'http://public-repo-1.hortonworks.com/HDP/centos5/RPM-GPG-KEY/RPM-GPG-KEY-Jenkins'
  # 'http://public-repo-1.hortonworks.com/HDP-UTILS-1.1.0.16/repos/centos6' \
  # 'http://public-repo-1.hortonworks.com/HDP/centos5/RPM-GPG-KEY/RPM-GPG-KEY-Jenkins'

push 'HDP-2.0.6.0-76' \
  'http://public-repo-1.hortonworks.com/HDP/centos6/2.x/updates/2.0.6.0' \
  'http://public-repo-1.hortonworks.com/HDP/centos6/RPM-GPG-KEY/RPM-GPG-KEY-Jenkins'

# ############## CLEANUP ##############

print 'Replace previous repositories'
# mv /etc/yum.repos.d.temp/epel.repo /etc/yum.repos.d
# mv /etc/yum.repos.d.temp/redhat.repo /etc/yum.repos.d
# mv /etc/yum.repos.d.temp/rh0l6.repo /etc/yum.repos.d
rm -rf /etc/yum.repos.d/*
mv /etc/yum.repos.d.temp/* /etc/yum.repos.d
rm -rf /etc/yum.repos.d.temp

unset http_proxy
yum clean metadata
yum repolist
