# Dockerfile for running shinken test scripts
# DO NOT BUILD IT BY YOURSELF, USE 
#`ryba prepare -m 'ryba/shinken/poller/*'`
FROM centos:latest

### PACKAGES ###
# add epel repo
RUN rpm -iUvh http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-9.noarch.rpm

RUN yum clean all && yum swap fakesystemd systemd
RUN yum -y update
# Install additionnal tools
RUN yum -y install sudo krb5-workstation wget libev libev-devel nmap-ncat jwhois cronie
# Install dev tools
RUN yum -y install git gcc gcc-c++ make snappy-devel openssl-devel expat-devel cyrus-sasl-devel mysql-devel
# Install php
RUN yum -y install php
# Install PERL
RUN yum -y install perl perl-devel perl-CPAN perl-libwww-perl perl-DBD-MySQL
# Install python
RUN yum -y install python-setuptools python-pip python-devel
# Disable require tty for sudo
RUN sed -i 's/Defaults.*requiretty/# Defaults requiretty/g' /etc/sudoers
# Install CPANM
#RUN curl -L http://cpanmin.us | perl - --sudo App::cpanminus
RUN wget http://nodejs.org/dist/latest/node-v7.9.0-linux-x64.tar.xz
RUN sudo tar --strip-components 1 -xJf node-v* -C /usr/local
# Install HDP repo
# RUN wget {{ shinken.poller.executor.hdp_repo }} -O /etc/yum.repos.d/hdp.repo --no-check-certificate 
# RUN sed -i 's/gpgcheck=1/gpgcheck=0/g' /etc/yum.repos.d/hdp.repo
# RUN yum -y update
# RUN yum -y install hive
# Install JAVA
# COPY {{ shinken.poller.executor.java.jdk.location }} /tmp/ryba-java/java.tar.gz
# RUN tar xzf /tmp/ryba-java/java.tar.gz -C /tmp/ryba-java
# RUN rm /tmp/ryba-java/java.tar.gz
# RUN mkdir /usr/java
# RUN mv /tmp/ryba-java/jdk{{ shinken.poller.executor.java.jdk.version }} /usr/java/{{ shinken.poller.executor.java.jdk.version }}
# RUN ln -sf /usr/java/{{ shinken.poller.executor.java.jdk.version }} /usr/java/latest
# RUN ln -sf /usr/java/{{ shinken.poller.executor.java.jdk.version }} /usr/java/default
# COPY java.sh /etc/profile.d/java.sh
# Install JAVA Policy
# COPY jce_policy-7/local_policy.jar /usr/java/default/jre/lib/security/local_policy.jar
# COPY jce_policy-7/US_export_policy.jar /usr/java/default/jre/lib/security/US_export_policy.jar
COPY id_rsa /root/.ssh/id_rsa
COPY id_rsa.pub /root/.ssh/id_rsa.pub
RUN chmod 600 /root/.ssh/id_rsa*
### LAYOUT ###
RUN useradd -ms /bin/bash {{ shinken.user.name }}
RUN echo "{{ shinken.user.name }}        ALL=(ALL)       NOPASSWD: ALL" >> /etc/sudoers

USER {{ shinken.user.name }}
WORKDIR /home/{{ shinken.user.name }}
RUN wget https://labs.consol.de/assets/downloads/nagios/check_mysql_health-2.2.2.tar.gz -O check_mysql.tar.gz
RUN tar xzvf check_mysql.tar.gz
RUN rm check_mysql.tar.gz
WORKDIR check_mysql_health-2.2.2
RUN ./configure --prefix=/home/{{ shinken.user.name }}
RUN make
RUN make install
RUN rm -rf check_mysql_health-2.2.2
WORKDIR /home/{{ shinken.user.name }}
# Downloading shinken-plugins
RUN git clone https://github.com/ryba-io/ryba-monitoring-plugins plugins
RUN rm -rf plugins/.git*
RUN mkdir -p plugins/mysql
RUN mv libexec/check_mysql_health plugins/mysql/check_health
RUN rm -rf check_mysql_health*
RUN rm -r libexec
WORKDIR /home/{{ shinken.user.name }}/plugins
CMD sudo crond -n
